apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: demo-python-app
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: demo-python-app
  policy:
    semver:
      range: ">= 0.0.0"
